### ISSUE TITLE
Lacking Documentation on how to use library

### ISSUE THREAD

**Issue by AdamHess** [bmcfee/muda#23]
Brian Just started reading through your paper and decided to take a look at the code (rather than just read a paper that describes the code.r) 

Your documentation (README) is a bit lacking on how to use your library. While an experienced developer can grok the code and make heads or tails of it; your best bet would be to include code samples of usage and explanation of your design patterns. 

This is a great example of the level of detail (while somewhat overkill) for a good project:

http://kenwheeler.github.io/slick/

https://docs.angularjs.org/api 

EDIT: I had a second look. I noticed you commented the code (which I think is fantastic) however, most practitioners would dive into the read me and clearly (markdown) readable usage.

**Comment by bmcfee** [comment]
Thanks for your interest in this package.

Is there something specifically unclear about the examples in the [documentation](http://muda.readthedocs.org/en/latest/?badge=latest)?

Note: documentation is a great way to contribute to open source, and I'd be happy to accept improvements via pull request.

**Comment by AdamHess** [comment]
Actually, that should do it! (I missed out on the docs icon on the page, my
mistake!)

thanks!

**Comment by bmcfee** [comment]
Happy to help.  I'll close this one out then.
