### ISSUE TITLE
deformers/data/drc_presets.json missing in pip install

### ISSUE THREAD

**Issue by tcwalther** [bmcfee/muda#24]
I just pip-installed muda into my virtualenv, and `drc_presets.json` was missing. I had a quick glimpse into `setup.py`, and it seems to be omitted. One option is to specify the `package_data` option, see http://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py

**Comment by bmcfee** [comment]
Good catch!  I'll fix it ASAP and put up a new version.  Thanks.
