### ISSUE TITLE
Better default values for LogspaceTimeStretch

### ISSUE THREAD

**Issue by justinsalamon** [bmcfee/muda#32]
This is minor, but the default values for the LogspaceTimeStretch deformer are 0.8 and 1.2. If one doesn't read the docs carefully one might assume this means stretching time by a factor of 0.8 (make audio shorter) to 1.2 (make audio longer), though in fact these values correspond to time-stretch factors between 1.74 and 2.3 (2^lower -- 2^upper), which seems somewhat arbitrary?

Setting the default values to -0.3 and +0.3 (for example) would give stretch factors in the range [0.81, 1.23] which perhaps makes more sense as default values?

**Comment by bmcfee** [comment]
You're quite right.  Thanks for catching that -- I'll tag it for the next minor release.
