### ISSUE TITLE
Errors in tests

### ISSUE THREAD

**Issue by mcartwright** [bmcfee/muda#53]
While adding tests for #40, I noticed what seem to be a couple of errors in the `test_deformers.py`.

In [`test_linear_pitchshift`](https://github.com/bmcfee/muda/blob/d171081bfdaea98989b51513776974ecc53ce2e0/tests/test_deformers.py#L358), 
shouldn't `assert lower <= d_tones <= 2.0**upper` be `assert lower <= d_tones <= upper`?

also, in [`__test_effect`](https://github.com/bmcfee/muda/blob/d171081bfdaea98989b51513776974ecc53ce2e0/tests/test_deformers.py#L371),
I think you intend for there to be an assert there, correct? i.e. `ann_orig == ann_new` -> `assert ann_orig == ann_new`

**Comment by bmcfee** [comment]
Thanks for catching that!
