### ISSUE TITLE
Can I load a wav file without JAMS?

### ISSUE THREAD

**Issue by cdyao** [bmcfee/muda#63]
Hi:

I would like to do data-augmentation for my bunch of wav files.
Can I use MUDA without JAMS file?
Thanks!

**Comment by bmcfee** [comment]
Note to self: we should add an example of this to the documentation.

**Comment by cdyao** [comment]
Glad to hear that an empty JAMS is a solution.
Expecting to see the example code since I still have no ideal how to do it.
Thanks for the reply!

**Comment by cdyao** [comment]
It turns out this is so simple. (Sorry I'm a rookie in this)

```
import jams

jam = jams.JAMS()
filename='some.wav'
j_orig = muda.load_jam_audio(jam, filename)
```
